import XCTest

#if DEBUG
  @testable import RedBlackTreeCollections
#else
  import RedBlackTreeCollections
#endif

#if COMPATIBLE_ATCODER_2025
  extension ConvenienceTests {
    func test_set_LT_GT() throws {
      var set = RedBlackTreeSet<Int>([0, 1, 2, 3, 4])
      XCTAssertEqual(set.count, 5)
      XCTAssertEqual(set.lessThan(-1), nil)
      XCTAssertEqual(set.greaterThan(-1), 0)
      XCTAssertEqual(set.lessThan(0), nil)
      XCTAssertEqual(set.greaterThan(0), 1)
      XCTAssertEqual(set.lessThan(1), 0)
      XCTAssertEqual(set.greaterThan(1), 2)
      XCTAssertEqual(set.lessThan(2), 1)
      XCTAssertEqual(set.greaterThan(2), 3)
      XCTAssertEqual(set.lessThan(3), 2)
      XCTAssertEqual(set.greaterThan(3), 4)
      XCTAssertEqual(set.lessThan(4), 3)
      XCTAssertEqual(set.greaterThan(4), nil)
      XCTAssertEqual(set.lessThan(5), 4)
      XCTAssertEqual(set.greaterThan(5), nil)
      XCTAssertEqual(set.remove(1), 1)
      XCTAssertEqual(set.remove(3), 3)
      XCTAssertEqual(set.remove(1), nil)
      XCTAssertEqual(set.remove(3), nil)
      XCTAssertEqual(set.elements, [0, 2, 4])
      XCTAssertEqual(set.lessThan(-1), nil)
      XCTAssertEqual(set.greaterThan(-1), 0)
      XCTAssertEqual(set.lessThan(0), nil)
      XCTAssertEqual(set.greaterThan(0), 2)
      XCTAssertEqual(set.lessThan(1), 0)
      XCTAssertEqual(set.greaterThan(1), 2)
      XCTAssertEqual(set.lessThan(2), 0)
      XCTAssertEqual(set.greaterThan(2), 4)
      XCTAssertEqual(set.lessThan(3), 2)
      XCTAssertEqual(set.greaterThan(3), 4)
      XCTAssertEqual(set.lessThan(4), 2)
      XCTAssertEqual(set.greaterThan(4), nil)
      XCTAssertEqual(set.lessThan(5), 4)
      XCTAssertEqual(set.greaterThan(5), nil)
      XCTAssertEqual(set.remove(2), 2)
      XCTAssertEqual(set.remove(1), nil)
      XCTAssertEqual(set.remove(2), nil)
      XCTAssertEqual(set.remove(3), nil)
      XCTAssertEqual(set.elements, [0, 4])
      XCTAssertEqual(set.lessThan(-1), nil)
      XCTAssertEqual(set.greaterThan(-1), 0)
      XCTAssertEqual(set.lessThan(0), nil)
      XCTAssertEqual(set.greaterThan(0), 4)
      XCTAssertEqual(set.lessThan(1), 0)
      XCTAssertEqual(set.greaterThan(1), 4)
      XCTAssertEqual(set.lessThan(2), 0)
      XCTAssertEqual(set.greaterThan(2), 4)
      XCTAssertEqual(set.lessThan(3), 0)
      XCTAssertEqual(set.greaterThan(3), 4)
      XCTAssertEqual(set.lessThan(4), 0)
      XCTAssertEqual(set.greaterThan(4), nil)
      XCTAssertEqual(set.lessThan(5), 4)
      XCTAssertEqual(set.greaterThan(5), nil)
      XCTAssertEqual(set.remove(0), 0)
      XCTAssertEqual(set.remove(1), nil)
      XCTAssertEqual(set.remove(2), nil)
      XCTAssertEqual(set.remove(3), nil)
      XCTAssertEqual(set.remove(4), 4)
      XCTAssertEqual(set.lessThan(-1), nil)
      XCTAssertEqual(set.greaterThan(-1), nil)
      XCTAssertEqual(set.lessThan(0), nil)
      XCTAssertEqual(set.greaterThan(0), nil)
      XCTAssertEqual(set.lessThan(1), nil)
      XCTAssertEqual(set.greaterThan(1), nil)
      XCTAssertEqual(set.lessThan(2), nil)
      XCTAssertEqual(set.greaterThan(2), nil)
      XCTAssertEqual(set.lessThan(3), nil)
      XCTAssertEqual(set.greaterThan(3), nil)
      XCTAssertEqual(set.lessThan(4), nil)
      XCTAssertEqual(set.greaterThan(4), nil)
      XCTAssertEqual(set.lessThan(5), nil)
      XCTAssertEqual(set.greaterThan(5), nil)
      XCTAssertEqual(set.elements, [])
    }

    func test_set_LE_GE() throws {
      var set = RedBlackTreeSet<Int>([0, 1, 2, 3, 4])
      XCTAssertEqual(set.count, 5)
      XCTAssertEqual(set.lessThanOrEqual(-1), nil)
      XCTAssertEqual(set.greaterThanOrEqual(-1), 0)
      XCTAssertEqual(set.lessThanOrEqual(0), 0)
      XCTAssertEqual(set.greaterThanOrEqual(0), 0)
      XCTAssertEqual(set.lessThanOrEqual(1), 1)
      XCTAssertEqual(set.greaterThanOrEqual(1), 1)
      XCTAssertEqual(set.lessThanOrEqual(2), 2)
      XCTAssertEqual(set.greaterThanOrEqual(2), 2)
      XCTAssertEqual(set.lessThanOrEqual(3), 3)
      XCTAssertEqual(set.greaterThanOrEqual(3), 3)
      XCTAssertEqual(set.lessThanOrEqual(4), 4)
      XCTAssertEqual(set.greaterThanOrEqual(4), 4)
      XCTAssertEqual(set.lessThanOrEqual(5), 4)
      XCTAssertEqual(set.greaterThanOrEqual(5), nil)
      XCTAssertEqual(set.remove(1), 1)
      XCTAssertEqual(set.remove(3), 3)
      XCTAssertEqual(set.remove(1), nil)
      XCTAssertEqual(set.remove(3), nil)
      XCTAssertEqual(set.elements, [0, 2, 4])
      XCTAssertEqual(set.lessThanOrEqual(-1), nil)
      XCTAssertEqual(set.greaterThanOrEqual(-1), 0)
      XCTAssertEqual(set.lessThanOrEqual(0), 0)
      XCTAssertEqual(set.greaterThanOrEqual(0), 0)
      XCTAssertEqual(set.lessThanOrEqual(1), 0)
      XCTAssertEqual(set.greaterThanOrEqual(1), 2)
      XCTAssertEqual(set.lessThanOrEqual(2), 2)
      XCTAssertEqual(set.greaterThanOrEqual(2), 2)
      XCTAssertEqual(set.lessThanOrEqual(3), 2)
      XCTAssertEqual(set.greaterThanOrEqual(3), 4)
      XCTAssertEqual(set.lessThanOrEqual(4), 4)
      XCTAssertEqual(set.greaterThanOrEqual(4), 4)
      XCTAssertEqual(set.lessThanOrEqual(5), 4)
      XCTAssertEqual(set.greaterThanOrEqual(5), nil)
      XCTAssertEqual(set.remove(2), 2)
      XCTAssertEqual(set.remove(1), nil)
      XCTAssertEqual(set.remove(2), nil)
      XCTAssertEqual(set.remove(3), nil)
      XCTAssertEqual(set.elements, [0, 4])
      XCTAssertEqual(set.lessThanOrEqual(-1), nil)
      XCTAssertEqual(set.greaterThanOrEqual(-1), 0)
      XCTAssertEqual(set.lessThanOrEqual(0), 0)
      XCTAssertEqual(set.greaterThanOrEqual(0), 0)
      XCTAssertEqual(set.lessThanOrEqual(1), 0)
      XCTAssertEqual(set.greaterThanOrEqual(1), 4)
      XCTAssertEqual(set.lessThanOrEqual(2), 0)
      XCTAssertEqual(set.greaterThanOrEqual(2), 4)
      XCTAssertEqual(set.lessThanOrEqual(3), 0)
      XCTAssertEqual(set.greaterThanOrEqual(3), 4)
      XCTAssertEqual(set.lessThanOrEqual(4), 4)
      XCTAssertEqual(set.greaterThanOrEqual(4), 4)
      XCTAssertEqual(set.lessThanOrEqual(5), 4)
      XCTAssertEqual(set.greaterThanOrEqual(5), nil)
      XCTAssertEqual(set.remove(0), 0)
      XCTAssertEqual(set.remove(1), nil)
      XCTAssertEqual(set.remove(2), nil)
      XCTAssertEqual(set.remove(3), nil)
      XCTAssertEqual(set.remove(4), 4)
      XCTAssertEqual(set.lessThanOrEqual(-1), nil)
      XCTAssertEqual(set.greaterThanOrEqual(-1), nil)
      XCTAssertEqual(set.lessThanOrEqual(0), nil)
      XCTAssertEqual(set.greaterThanOrEqual(0), nil)
      XCTAssertEqual(set.lessThanOrEqual(1), nil)
      XCTAssertEqual(set.greaterThanOrEqual(1), nil)
      XCTAssertEqual(set.lessThanOrEqual(2), nil)
      XCTAssertEqual(set.greaterThanOrEqual(2), nil)
      XCTAssertEqual(set.lessThanOrEqual(3), nil)
      XCTAssertEqual(set.greaterThanOrEqual(3), nil)
      XCTAssertEqual(set.lessThanOrEqual(4), nil)
      XCTAssertEqual(set.greaterThanOrEqual(4), nil)
      XCTAssertEqual(set.lessThanOrEqual(5), nil)
      XCTAssertEqual(set.greaterThanOrEqual(5), nil)
      XCTAssertEqual(set.elements, [])
    }
  }

  extension ConvenienceTests {
    func test_Multiset_LT_GT() throws {
      var set = RedBlackTreeMultiSet<Int>([0, 1, 2, 3, 4])
      XCTAssertEqual(set.count, 5)
      XCTAssertEqual(set.lessThan(-1), nil)
      XCTAssertEqual(set.greaterThan(-1), 0)
      XCTAssertEqual(set.lessThan(0), nil)
      XCTAssertEqual(set.greaterThan(0), 1)
      XCTAssertEqual(set.lessThan(1), 0)
      XCTAssertEqual(set.greaterThan(1), 2)
      XCTAssertEqual(set.lessThan(2), 1)
      XCTAssertEqual(set.greaterThan(2), 3)
      XCTAssertEqual(set.lessThan(3), 2)
      XCTAssertEqual(set.greaterThan(3), 4)
      XCTAssertEqual(set.lessThan(4), 3)
      XCTAssertEqual(set.greaterThan(4), nil)
      XCTAssertEqual(set.lessThan(5), 4)
      XCTAssertEqual(set.greaterThan(5), nil)
      XCTAssertEqual(set.removeAll(1), 1)
      XCTAssertEqual(set.removeAll(3), 3)
      XCTAssertEqual(set.removeAll(1), nil)
      XCTAssertEqual(set.removeAll(3), nil)
      XCTAssertEqual(set.sorted(), [0, 2, 4])
      XCTAssertEqual(set.lessThan(-1), nil)
      XCTAssertEqual(set.greaterThan(-1), 0)
      XCTAssertEqual(set.lessThan(0), nil)
      XCTAssertEqual(set.greaterThan(0), 2)
      XCTAssertEqual(set.lessThan(1), 0)
      XCTAssertEqual(set.greaterThan(1), 2)
      XCTAssertEqual(set.lessThan(2), 0)
      XCTAssertEqual(set.greaterThan(2), 4)
      XCTAssertEqual(set.lessThan(3), 2)
      XCTAssertEqual(set.greaterThan(3), 4)
      XCTAssertEqual(set.lessThan(4), 2)
      XCTAssertEqual(set.greaterThan(4), nil)
      XCTAssertEqual(set.lessThan(5), 4)
      XCTAssertEqual(set.greaterThan(5), nil)
      XCTAssertEqual(set.removeAll(2), 2)
      XCTAssertEqual(set.removeAll(1), nil)
      XCTAssertEqual(set.removeAll(2), nil)
      XCTAssertEqual(set.removeAll(3), nil)
      XCTAssertEqual(set.sorted(), [0, 4])
      XCTAssertEqual(set.lessThan(-1), nil)
      XCTAssertEqual(set.greaterThan(-1), 0)
      XCTAssertEqual(set.lessThan(0), nil)
      XCTAssertEqual(set.greaterThan(0), 4)
      XCTAssertEqual(set.lessThan(1), 0)
      XCTAssertEqual(set.greaterThan(1), 4)
      XCTAssertEqual(set.lessThan(2), 0)
      XCTAssertEqual(set.greaterThan(2), 4)
      XCTAssertEqual(set.lessThan(3), 0)
      XCTAssertEqual(set.greaterThan(3), 4)
      XCTAssertEqual(set.lessThan(4), 0)
      XCTAssertEqual(set.greaterThan(4), nil)
      XCTAssertEqual(set.lessThan(5), 4)
      XCTAssertEqual(set.greaterThan(5), nil)
      XCTAssertEqual(set.removeAll(0), 0)
      XCTAssertEqual(set.removeAll(1), nil)
      XCTAssertEqual(set.removeAll(2), nil)
      XCTAssertEqual(set.removeAll(3), nil)
      XCTAssertEqual(set.removeAll(4), 4)
      XCTAssertEqual(set.lessThan(-1), nil)
      XCTAssertEqual(set.greaterThan(-1), nil)
      XCTAssertEqual(set.lessThan(0), nil)
      XCTAssertEqual(set.greaterThan(0), nil)
      XCTAssertEqual(set.lessThan(1), nil)
      XCTAssertEqual(set.greaterThan(1), nil)
      XCTAssertEqual(set.lessThan(2), nil)
      XCTAssertEqual(set.greaterThan(2), nil)
      XCTAssertEqual(set.lessThan(3), nil)
      XCTAssertEqual(set.greaterThan(3), nil)
      XCTAssertEqual(set.lessThan(4), nil)
      XCTAssertEqual(set.greaterThan(4), nil)
      XCTAssertEqual(set.lessThan(5), nil)
      XCTAssertEqual(set.greaterThan(5), nil)
      XCTAssertEqual(set.sorted(), [])
    }

    func test_Multiset_LE_GE() throws {
      var set = RedBlackTreeMultiSet<Int>([0, 1, 2, 3, 4])
      XCTAssertEqual(set.count, 5)
      XCTAssertEqual(set.lessThanOrEqual(-1), nil)
      XCTAssertEqual(set.greaterThanOrEqual(-1), 0)
      XCTAssertEqual(set.lessThanOrEqual(0), 0)
      XCTAssertEqual(set.greaterThanOrEqual(0), 0)
      XCTAssertEqual(set.lessThanOrEqual(1), 1)
      XCTAssertEqual(set.greaterThanOrEqual(1), 1)
      XCTAssertEqual(set.lessThanOrEqual(2), 2)
      XCTAssertEqual(set.greaterThanOrEqual(2), 2)
      XCTAssertEqual(set.lessThanOrEqual(3), 3)
      XCTAssertEqual(set.greaterThanOrEqual(3), 3)
      XCTAssertEqual(set.lessThanOrEqual(4), 4)
      XCTAssertEqual(set.greaterThanOrEqual(4), 4)
      XCTAssertEqual(set.lessThanOrEqual(5), 4)
      XCTAssertEqual(set.greaterThanOrEqual(5), nil)
      XCTAssertEqual(set.removeAll(1), 1)
      XCTAssertEqual(set.removeAll(3), 3)
      XCTAssertEqual(set.removeAll(1), nil)
      XCTAssertEqual(set.removeAll(3), nil)
      XCTAssertEqual(set.sorted(), [0, 2, 4])
      XCTAssertEqual(set.lessThanOrEqual(-1), nil)
      XCTAssertEqual(set.greaterThanOrEqual(-1), 0)
      XCTAssertEqual(set.lessThanOrEqual(0), 0)
      XCTAssertEqual(set.greaterThanOrEqual(0), 0)
      XCTAssertEqual(set.lessThanOrEqual(1), 0)
      XCTAssertEqual(set.greaterThanOrEqual(1), 2)
      XCTAssertEqual(set.lessThanOrEqual(2), 2)
      XCTAssertEqual(set.greaterThanOrEqual(2), 2)
      XCTAssertEqual(set.lessThanOrEqual(3), 2)
      XCTAssertEqual(set.greaterThanOrEqual(3), 4)
      XCTAssertEqual(set.lessThanOrEqual(4), 4)
      XCTAssertEqual(set.greaterThanOrEqual(4), 4)
      XCTAssertEqual(set.lessThanOrEqual(5), 4)
      XCTAssertEqual(set.greaterThanOrEqual(5), nil)
      XCTAssertEqual(set.removeAll(2), 2)
      XCTAssertEqual(set.removeAll(1), nil)
      XCTAssertEqual(set.removeAll(2), nil)
      XCTAssertEqual(set.removeAll(3), nil)
      XCTAssertEqual(set.sorted(), [0, 4])
      XCTAssertEqual(set.lessThanOrEqual(-1), nil)
      XCTAssertEqual(set.greaterThanOrEqual(-1), 0)
      XCTAssertEqual(set.lessThanOrEqual(0), 0)
      XCTAssertEqual(set.greaterThanOrEqual(0), 0)
      XCTAssertEqual(set.lessThanOrEqual(1), 0)
      XCTAssertEqual(set.greaterThanOrEqual(1), 4)
      XCTAssertEqual(set.lessThanOrEqual(2), 0)
      XCTAssertEqual(set.greaterThanOrEqual(2), 4)
      XCTAssertEqual(set.lessThanOrEqual(3), 0)
      XCTAssertEqual(set.greaterThanOrEqual(3), 4)
      XCTAssertEqual(set.lessThanOrEqual(4), 4)
      XCTAssertEqual(set.greaterThanOrEqual(4), 4)
      XCTAssertEqual(set.lessThanOrEqual(5), 4)
      XCTAssertEqual(set.greaterThanOrEqual(5), nil)
      XCTAssertEqual(set.removeAll(0), 0)
      XCTAssertEqual(set.removeAll(1), nil)
      XCTAssertEqual(set.removeAll(2), nil)
      XCTAssertEqual(set.removeAll(3), nil)
      XCTAssertEqual(set.removeAll(4), 4)
      XCTAssertEqual(set.lessThanOrEqual(-1), nil)
      XCTAssertEqual(set.greaterThanOrEqual(-1), nil)
      XCTAssertEqual(set.lessThanOrEqual(0), nil)
      XCTAssertEqual(set.greaterThanOrEqual(0), nil)
      XCTAssertEqual(set.lessThanOrEqual(1), nil)
      XCTAssertEqual(set.greaterThanOrEqual(1), nil)
      XCTAssertEqual(set.lessThanOrEqual(2), nil)
      XCTAssertEqual(set.greaterThanOrEqual(2), nil)
      XCTAssertEqual(set.lessThanOrEqual(3), nil)
      XCTAssertEqual(set.greaterThanOrEqual(3), nil)
      XCTAssertEqual(set.lessThanOrEqual(4), nil)
      XCTAssertEqual(set.greaterThanOrEqual(4), nil)
      XCTAssertEqual(set.lessThanOrEqual(5), nil)
      XCTAssertEqual(set.greaterThanOrEqual(5), nil)
      XCTAssertEqual(set.sorted(), [])
    }
  }

  extension ConvenienceTests {
    func testRedBlackTreeConveniences() throws {
      let numbers: RedBlackTreeSet = [1, 3, 5, 7, 9]

      XCTAssertEqual(numbers.lessThan(4), 3)
      XCTAssertEqual(numbers.lessThanOrEqual(4), 3)
      XCTAssertEqual(numbers.lessThan(5), 3)
      XCTAssertEqual(numbers.lessThanOrEqual(5), 5)

      XCTAssertEqual(numbers.greaterThan(6), 7)
      XCTAssertEqual(numbers.greaterThanOrEqual(6), 7)
      XCTAssertEqual(numbers.greaterThan(5), 7)
      XCTAssertEqual(numbers.greaterThanOrEqual(5), 5)
    }
  }

  extension ConvenienceTests {
    func testEnumerate() throws {
      var set: RedBlackTreeSet<Int> = [1, 2, 3, 4, 5, 6]
      set
        .forEach { i, v in
          set.remove(at: i)
        }
      XCTAssertEqual(set, [])
    }
  }
  extension ConvenienceTests {
  }

  extension ConvenienceTests {
  }
#endif
