name: Swift

on:
  push:
    branches:
      - main
      - compatible/AtCoder/2025
  pull_request:
    branches:
      - main
      - compatible/AtCoder/2025

jobs:
  documentation:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Swift
        uses: SwiftyLab/setup-swift@latest

      - name: Build documentation
        run: >-
          swift package --allow-writing-to-directory .build/documentation
          generate-documentation
          --target RedBlackTreeCollections
          --output-path .build/documentation
          --transform-for-static-hosting
          --hosting-base-path swift-ac-collections
          --warnings-as-errors

      - name: Archive documentation
        run: >-
          tar -czf .build/RedBlackTreeCollections-documentation.tar.gz
          -C .build/documentation .

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: RedBlackTreeCollections-documentation
          path: .build/RedBlackTreeCollections-documentation.tar.gz
          if-no-files-found: error

  debug:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Swift
        uses: SwiftyLab/setup-swift@latest

      - name: Run tests
        run: swift test -c debug

  release:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Swift
        uses: SwiftyLab/setup-swift@latest

      - name: Run tests
        run: swift test -c release

  address-sanitizer:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Swift
        uses: SwiftyLab/setup-swift@latest

      - name: Run tests with Address Sanitizer
        env:
          ASAN_OPTIONS: detect_leaks=0
        run: swift test -c debug --sanitize address
